local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/CryoScript/CryoHublib/main/Cryo%20Hub.lua"))()

local Window = Library:CreateWindow("CH Title", "Main")

local Tab1 = Window:CreateTab("M", "Main")
local Tab2 = Window:CreateTab("O", "Other")
local Tab3 = Window:CreateTab("A", "Auto")

local Section1 = Tab1:CreateSection()
local Section2 = Tab1:CreateSection()

Section1:CreateLabel("Test Label")
Section1:CreateLabel("Test Label 2")
Section2:CreateButton("Test Button", function()
    print("Button Works")
end)
Section2:CreateButton("Test Button 2", function()
    print("Button 2 Works")
end)
Section1:CreateToggle("Test Toggle", function(state)
    print(state)
end)
Section2:CreateToggle("Test Toggle 2", function(state)
    print(state)
end)
Section1:CreateSlider("Test Slider", 0, 100, function(value)
    print(value)
end)
Section2:CreateSlider("Test Slider 2", 90, 430, function(value)
    print(value)
end)
Section1:CreateBox("Test Box", function(input)
    print(input)
end)
Section2:CreateBox("Test Box 2", function(input)
    print(input)
end)
Section1:CreateDropdown("Test Dropdown", {"We","Love","Cryo"}, function(selected)
    print(selected)
end)
Section2:CreateDropdown("Test Dropdown 2", {"We","Love","Cryo"}, function(selected)
    print(selected)
end)
