local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/CryoScript/CryoHublib/main/Saturn%20Cryo%20Hub.lua"))()
local Window = Library:CreateWindow()
local SettingsTab = Window:CreateTab("Settings","15412919808")
local LocalPlayerTab = Window:CreateTab("Local Player","15410847404")
local Section1 = LocalPlayerTab:CreateSection()

Section1:CreateSection("Buttons")
Section1:CreateButton("Button",function()
	print("Hello!")
end)
Section1:CreateSection("Toggles")
Section1:CreateToggle("Toggle",function(state)
	print(state)
end)
Section1:CreateSection("Sliders")
Section1:CreateSlider("Slider",150,function(value)
	print(value)
end)
Section1:CreateSection("Labels")
Section1:CreateLabel("Label")
Section1:CreateSection("Boxes")
Section1:CreateBox("Box",function(input)
	print(input)
end)
